# Variables to be replaced by Environment
# APP_NAMESPACE_REGISTRY
# APP_HOST_URL
# APP_PROFILE
# 80
# APP_PROJECT_KUBE_NAMESPACE
# APP_INGRESS_NAME
# CI_COMMIT_TAG
# CI_PROJECT_NAME


#Create the namespace, if exists buid will pass
apiVersion: v1
kind: Namespace
metadata:
  name: APP_PROJECT_KUBE_NAMESPACE
  labels:
    name: APP_PROJECT_KUBE_NAMESPACE

---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUlYVENDQmtXZ0F3SUJBZ0lUV0FBQkRBTzlhSkIyWGR6NHNBQUFBQUVNQXpBTkJna3Foa2lHOXcwQkFRc0YKQURCd01Rc3dDUVlEVlFRR0V3SkVSVEVRTUE0R0ExVUVDQk1IU0dGdFluVnlaekVRTUE0R0ExVUVCeE1IU0dGdApZblZ5WnpFVU1CSUdBMVVFQ2hNTFNHRnRZblZ5WjFOMVpXUXhDekFKQmdOVkJBc1RBa2xVTVJvd0dBWURWUVFECkV4RklVMFJISUZOMVlpQkRRU0F3TVNCMk5EQWVGdzB4T1RBek1qY3dOekF4TURKYUZ3MHlNVEF6TWpZd056QXgKTURKYU1JR2NNUXN3Q1FZRFZRUUdFd0pDVWpFTE1Ba0dBMVVFQ0JNQ1UxQXhFakFRQmdOVkJBY1RDVk5oYnlCUQpZWFZzYnpFTk1Bc0dBMVVFQ3hNRVNGTkVSekVNTUFvR0ExVUVDeE1EVWxORk1SMHdHd1lEVlFRRERCUXFMbk5oCmJ5NW9ZVzFpZFhKbmMzVmtMbU52YlRFd01DNEdDU3FHU0liM0RRRUpBUlloVTBGUExVbE9SbEpCVTFSU1ZVTlUKVlZKRlFHRnNhV0Z1WTJFdVkyOXRMbUp5TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQwpBUUVBclRxUjU3MlZSTnliSkNjaTFhTWhoSEtUaEN6YUxNeDM4S1VFQlNVZFVVV09uclBEWjgzTkZWYU9YMk1xCk5KQ2tpU3hWanlRTTA5a3VMTWpiakNmM3BJeTBqMm5tbnNwcXA3VU5oQ2NkQ2tGbmpvZGV0cXFOaXN2dDdjZFEKS3VOWEpobXkyZnlieEcvQ2pFRHZQVklDMkhyejdER05QTU96OFp3d0dob3VMSzRPRjJnT0hpSW8wblJDeGl6UAp3NEFQaG1PYWJwSTFncVNBK1NzdTBsOThmZ29iaEN3ZU1Wa015V1E5OTFDbkNjem9Gc3ZTUTM1R1BSempJMmZ6ClNqdlV0L3JVQjZWUmRHbjZ0WkdzR1NrWlUwcjFvdk50UXZsL25kYlRvQ0VQTElvOTdKR1phamJCV0dlMVk2T1gKNXJhd2R5bDlZTzQ1N2l2cG9XU0JRVDRKQndJREFRQUJvNElEd1RDQ0E3MHdHd1lKS3dZQkJBR0NOeFVLQkE0dwpEREFLQmdnckJnRUZCUWNEQVRBOUJna3JCZ0VFQVlJM0ZRY0VNREF1QmlZckJnRUVBWUkzRlFpRjA1dDNob211ClZvV2Rud3lEc0w0MWg3SzBMRnVIb1kwQ2daSFZmQUlCWkFJQkVUQ0NBV1VHQ0NzR0FRVUZCd0VCQklJQlZ6Q0MKQVZNd2diZ0dDQ3NHQVFVRkJ6QUNob0dyYkdSaGNEb3ZMeTlEVGoxSVUwUkhKVEl3VTNWaUpUSXdRMEVsTWpBdwpNU1V5TUhZMExFTk9QVUZKUVN4RFRqMVFkV0pzYVdNbE1qQkxaWGtsTWpCVFpYSjJhV05sY3l4RFRqMVRaWEoyCmFXTmxjeXhEVGoxRGIyNW1hV2QxY21GMGFXOXVMRVJEUFdoelpHY3RZV1FzUkVNOWFXNTBQMk5CUTJWeWRHbG0KYVdOaGRHVS9ZbUZ6WlQ5dlltcGxZM1JEYkdGemN6MWpaWEowYVdacFkyRjBhVzl1UVhWMGFHOXlhWFI1TUVvRwpDQ3NHQVFVRkJ6QUNoajVvZEhSd09pOHZjR3RwTVM1b2MyUm5MV0ZrTG1sdWRDOURaWEowUkdGMFlTOUlVMFJICkpUSXdVM1ZpSlRJd1EwRWxNakF3TVNVeU1IWTBMbU55ZERCS0JnZ3JCZ0VGQlFjd0FvWSthSFIwY0RvdkwzQnIKYVRJdWFITmtaeTFoWkM1cGJuUXZRMlZ5ZEVSaGRHRXZTRk5FUnlVeU1GTjFZaVV5TUVOQkpUSXdNREVsTWpCMgpOQzVqY25Rd0hRWURWUjBPQkJZRUZHU0JrczZnbHBqMmpSRVRmZmNaalBRbU9vL2xNQTRHQTFVZER3RUIvd1FFCkF3SUZvREFmQmdOVkhSRUVHREFXZ2hRcUxuTmhieTVvWVcxaWRYSm5jM1ZrTG1OdmJUQ0NBVzRHQTFVZEh3U0MKQVdVd2dnRmhNSUlCWGFDQ0FWbWdnZ0ZWaG9IU2JHUmhjRG92THk5RFRqMUlVMFJISlRJd1UzVmlKVEl3UTBFbApNakF3TVNVeU1IWTBMRU5PUFVoVFJFY2xNakJUZFdJbE1qQkRRU1V5TURBeEpUSXdkalFzUTA0OVEwUlFMRU5PClBWQjFZbXhwWXlVeU1FdGxlU1V5TUZObGNuWnBZMlZ6TEVOT1BWTmxjblpwWTJWekxFTk9QVU52Ym1acFozVnkKWVhScGIyNHNSRU05YUhOa1p5MWhaQ3hFUXoxcGJuUS9ZMlZ5ZEdsbWFXTmhkR1ZTWlhadlkyRjBhVzl1VEdsegpkRDlpWVhObFAyOWlhbVZqZEVOc1lYTnpQV05TVEVScGMzUnlhV0oxZEdsdmJsQnZhVzUwaGo1b2RIUndPaTh2CmNHdHBNUzVvYzJSbkxXRmtMbWx1ZEM5RFpYSjBSR0YwWVM5SVUwUkhKVEl3VTNWaUpUSXdRMEVsTWpBd01TVXkKTUhZMExtTnliSVkrYUhSMGNEb3ZMM0JyYVRJdWFITmtaeTFoWkM1cGJuUXZRMlZ5ZEVSaGRHRXZTRk5FUnlVeQpNRk4xWWlVeU1FTkJKVEl3TURFbE1qQjJOQzVqY213d0h3WURWUjBqQkJnd0ZvQVUxazBWamJObjg4ZWtDZzRjClBVV3VqSDAyVnhjd0V3WURWUjBsQkF3d0NnWUlLd1lCQlFVSEF3RXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnSUIKQUxENGU2bFVzbzR3dUZ1VDh0RXNHWXVMT0ZieDg5d3FJUjNTUXhac09VaXcwbFlacU5DaXoxeGEwVGYxTTZlRApDeGc1SEczU1hXejhMOHlqby9LTXlPQUM5OFJLUnBySDV6aUplQU1LN0lBQlRXR1dpOEZKajBKSTRTckg0RTZTCll3SlNXVmZPSGlLcXN4Q1FER0pJVzIvZFlZTGIrZUtlZmRsQUFQRnJsR01WYjIzMndGcDJOQ3RzNFRyVnVwS1YKZDc5ejFOdkd3cktVQjdOMHlGTkJWZmpMUWxLeU84TVhMc3BoVjhvbjhvSGNyWktVMUdBSmN6M0hWaEZldlJqcwo3Qk5rVnZDajFsYXRqZVovc3JsTzY1UGZMeTFLRXc2NFNFWkVpc1J1YlByY0hiTlFBMDliVDNnYXFndXZUYnFaCm8wS1lIMHZjQVg5cmJLRmNmOTNrTmEvdDRxUWw0Ly9ORS9YeVFxNFgzeFRuMXVGcHp3UC9sdm5IVkFFTXh5TVUKckkrK1M3R2EzTS9jNGhHQWJ4MkxheGg4d3RFK211VE5DMSs0bWc3ejQ1ck5GdjRrZnZhM1FoamtIem9Bd09qVQpXYUZkK0IvNnR1TENxdmd6VExYaW16QXVRRjJpTysxazA5S2JIbzYvM3RHN0dBdTdOVURMY2gwWG5yM2trYytQClZGMldxM2xXZHkrWVYzam1LbG9xVnkwSzNyU1JJSmNVM0I0NHhUdlVERmJlWC82V21kVTl6NEtpVmNHYUI3Um4KMEVDa3BmRkh5YllweDlmVUtGdFUxTVNmcmlIUTdQbkpNM2c3d2FlQWV1TDlFaE9ENHo2d3hHSkdRUmJ5UEs0QwpGYjRYdGd5YjlHWGVBQWhJZG5DNjYyOHZ3cFE3bWNBVm5Ub2xpSDcwdXBvbQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRQ3RPcEhudlpWRTNKc2sKSnlMVm95R0VjcE9FTE5vc3pIZndwUVFGSlIxUlJZNmVzOE5uemMwVlZvNWZZeW8wa0tTSkxGV1BKQXpUMlM0cwp5TnVNSi9la2pMU1BhZWFleW1xbnRRMkVKeDBLUVdlT2gxNjJxbzJLeSszdHgxQXE0MWNtR2JMWi9KdkViOEtNClFPODlVZ0xZZXZQc01ZMDh3N1B4bkRBYUdpNHNyZzRYYUE0ZUlpalNkRUxHTE0vRGdBK0dZNXB1a2pXQ3BJRDUKS3k3U1gzeCtDaHVFTEI0eFdRekpaRDMzVUtjSnpPZ1d5OUpEZmtZOUhPTWpaL05LTzlTMyt0UUhwVkYwYWZxMQprYXdaS1JsVFN2V2k4MjFDK1grZDF0T2dJUThzaWozc2tabHFOc0ZZWjdWam81Zm10ckIzS1gxZzdqbnVLK21oClpJRkJQZ2tIQWdNQkFBRUNnZ0VBU1pKSWlYM1JPYS9nREJpN0NMVUI5VGljUWxTeVRMaUNjQ2dGYnhIMlE2QWgKRkhJUW1iT2tXRjJzbGdLTjJFbGVPQXdtUW1iek03NVhpQm0rZE9ZOG5SeE5TMk9VMlBmckdGTWk3RytZTzlUUApZSTlKd0pickNubldFVmpIU1kvSVlad2tnOFJ2ZTV4anFpR2grZzhzdWpodUJIQi9KY0dRV1JzV3F0OVhvUTJRCmJJMTBCNFMyMGp0bDBpVEc5UDlxYkkySzZuMTdYVVo1NVFTcVorbmM2cVRlaFpueWJ3OVBERG5JT082ME9pS3YKdnE1T2h5YkNlS2JuVnFZd2o5eFZ1YTkrdkRXa3lrUGpPbGdxK0ZzSk5MVEhZenhldTlTUTl0YU1pK21FazN6QQp0RzgrazZnMi9naTFtMnVCZjFobXp4aUhkOHd3cFA4U2VNdS9jK3NVNFFLQmdRRFh2QU05UlE3UEZoam8rTFFlCkwxSjZPRE1CL21vLzlaTXd4Njd6Sm9OVS9jTjdzWmVkaEdZczlsZUUxbThOSVBpbmhMUnBrRlRUVEloMXNHWS8KVmdSMkJBN0xZRG1scTh0bE00dHNlTy9OY1IxcitCWm1ZZVN4OS9nSHZMVEp4aUcrT3dpcGhTUmFFM0FaNVZ2UwpaZkpkK2d4ejJOcHM3WSt2L0ZaQS9pb01yd0tCZ1FETmo1bHJaRkV3ekhmNCtnNE1qN2tjNU1CV1NrdkdiMkZECnVlNjZPTlhEZ0tDWnpadnp3eXdHbjQ0Ym00SzZqVzk4bmZTaHVvYkFMMC9MOXpiVmxFTE1BUjBXdW93endqWTgKTXZ6V00xMFBWSTZEbll3OHdYTGQ2aFVqNXpGNkY0QTFPSFlFbVZvTGlFdDQ4bHdJdW1GV3EwRHJsUFR5M2NYdQpWbmlnTE9oUEtRS0JnQTNZWlNUVGY4WE9sejZzWjNMZ2VweVphcnlnQlZXaGZ4Yk1XZkFFOHJ6THBIWVZ5Yk0wClFoSjBwTjFEbmREcjRzbHRmTjZoZ3JBazQwVWFVeFdSZ2F2SlN1SEdoU3lhdit6NHgrUG9Sd3VhVE5jWER1ajMKTTJRd2s5eDdRZWNKTGpVMU9MTVlkbUxKaUpKQTVBbTJ2VDFHeFBIU1l3SkdwTWdZbTdpRUYxTEZBb0dBTzRIQwpqQkF5WU1vUVFRZENZZWlKVWcvMmpnUmNBMG5qQWxRbEE4dklOaHhhWWF2ZjVhVXViWXhxK3hyOXNUdVlkcDdUClhxNDhyQTRHTDZtVk9pYjlYMGxEUG4wcWNTRmJ5Zm1Jc0FtV2V3V2phLzZEeG1MSitldjF5cnIyMjcxSjVCNUEKSy95bzBJWFlNMThWdllFWEJKdjI0enZ2M1E3T2FieW1sdGZwT0dFQ2dZQW1rclVLK0NiWm9lUlhZUlI2NjU2eAp6bG9jeU82ZW1TWTF0MkVPRVo5cFlkY2ExcTUvaFR4YjVrVVRzLzdhRHZubkx3cUltam9OTGJEditrWjQ2cDh3CnlOKzZtU3VXT3hTUk42UTZhZW84ODcvTTlmcTRyMjdad21pSDNyZkFyUUY5SlpaV3lDSmFxQnhuNDFuSWV4b20KajhzVjNQQUVFVW9NMXNsS0x5dGFiUT09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
kind: Secret
metadata:
  name: rse-wildcard-ssl
  namespace: APP_PROJECT_KUBE_NAMESPACE
type: kubernetes.io/tls

---

apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    generation: 2
    name: APP_INGRESS_NAME
    namespace: APP_PROJECT_KUBE_NAMESPACE
  spec:
    backend:
      serviceName: default-https-backend
      servicePort: 443
    rules:
    - host: APP_HOST_URL
      http:
        paths:
        - backend:
            serviceName: CI_PROJECT_NAME
            servicePort: 80
          path: /
    tls:
    - hosts:
      - APP_HOST_URL
      secretName: rse-wildcard-ssl
  status:
    loadBalancer:
      ingress:
      - ip: 10.121.224.151
      - ip: 10.121.224.152
      - ip: 10.121.224.153
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: CI_PROJECT_NAME
  name: CI_PROJECT_NAME
  namespace: APP_PROJECT_KUBE_NAMESPACE
spec:
  replicas: 2
  selector:
    matchLabels:
      app: CI_PROJECT_NAME
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: CI_PROJECT_NAME
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                - rsesaovl151
      containers:
      - env:
        - name: https_proxy
          value: 10.121.224.252:8080
        - name: http_proxy
          value: 10.121.224.252:8080
        - name: PORT
          value: "80"
        # APP Env comes below this comment
        image: docker-images.sao.hamburgsud.com/CI_PROJECT_NAME:CI_COMMIT_TAG-APP_PROFILE
        imagePullPolicy: IfNotPresent
        name: CI_PROJECT_NAME
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 80
          failureThreshold: 3
        resources:
          limits:
            cpu: 500m
            memory: 2500Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          privileged: true
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: APP_NAMESPACE_REGISTRY
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
